-- db/seed.sql
--
-- Runs ONCE, on first boot only, when the data directory is empty.
-- The postgres entrypoint executes this as POSTGRES_USER against POSTGRES_DB,
-- with psql -v ON_ERROR_STOP=1 (any error aborts the whole init).
--
-- To re-run after editing:  docker compose down -v && docker compose up -d

BEGIN;

-- ---------------------------------------------------------------------------
-- categories
--   parent_id is the SELF-REFERENCING FK: a category can sit under another
--   category. It must be nullable, otherwise no row could ever be the root.
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text NOT NULL UNIQUE,
    parent_id integer REFERENCES categories (id) ON DELETE SET NULL
);

CREATE INDEX ON categories (parent_id);

-- ---------------------------------------------------------------------------
-- products
--   category_id is the NULLABLE FK: an uncategorised product is legal.
--   ON DELETE SET NULL means deleting a category orphans its products
--   instead of blocking the delete.
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    price       numeric(10,2) NOT NULL CHECK (price >= 0),
    category_id integer REFERENCES categories (id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON products (category_id);

-- ---------------------------------------------------------------------------
-- customers
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      text NOT NULL UNIQUE,
    full_name  text NOT NULL,
    city       text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- orders
--   customer_id is NOT NULL + ON DELETE RESTRICT: an order must belong to
--   someone, and you cannot delete a customer who has order history.
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
    status      text NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled')),
    placed_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON orders (customer_id);

-- ---------------------------------------------------------------------------
-- order_items  -- the join table
--   COMPOSITE PRIMARY KEY (order_id, product_id): a product appears at most
--   once per order; raise quantity instead of adding a second row.
--   TWO FOREIGN KEYS, with deliberately different delete rules:
--     - orders   ON DELETE CASCADE  : items are meaningless without the order
--     - products ON DELETE RESTRICT : never silently erase sales history
--   unit_price is a SNAPSHOT of the price at purchase time, not a lookup
--   into products.price -- prices change, invoices must not.
-- ---------------------------------------------------------------------------
CREATE TABLE order_items (
    order_id   integer NOT NULL REFERENCES orders (id)   ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    quantity   integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (order_id, product_id)
);

-- The composite PK already indexes (order_id, ...), so lookups by order are
-- covered. Lookups by product are not -- hence this second index.
CREATE INDEX ON order_items (product_id);


-- ===========================================================================
-- SAMPLE DATA
-- Inserted parent-first so every FK has something to point at.
-- ===========================================================================

-- Two roots and their children (self-referencing FK in action)
INSERT INTO categories (id, name, parent_id) VALUES
    (1, 'Electronics',    NULL),
    (2, 'Computers',      1),
    (3, 'Laptops',        2),
    (4, 'Home & Kitchen', NULL),
    (5, 'Coffee',         4);

-- Note the last row: category_id NULL (the nullable FK in action)
INSERT INTO products (id, name, price, category_id) VALUES
    (1, 'ThinkPad X1 Carbon', 14500.00, 3),
    (2, 'MacBook Air 13"',    12900.00, 3),
    (3, 'USB-C Hub 7-in-1',     349.90, 2),
    (4, 'Espresso Machine',    2199.00, 5),
    (5, 'Gift Card 500 MAD',    500.00, NULL);

INSERT INTO customers (id, email, full_name, city) VALUES
    (1, 'amine@example.com',  'Amine Benali',   'Casablanca'),
    (2, 'sara@example.com',   'Sara El Fassi',  'Rabat'),
    (3, 'youssef@example.com','Youssef Idrissi', NULL);

INSERT INTO orders (id, customer_id, status, placed_at) VALUES
    (1, 1, 'shipped',   now() - interval '10 days'),
    (2, 1, 'paid',      now() - interval '3 days'),
    (3, 2, 'pending',   now() - interval '1 day'),
    (4, 3, 'cancelled', now() - interval '20 days');

-- Order 1, item 1: unit_price is LOWER than products.price today --
-- that is the snapshot doing its job, not a bug.
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES
    (1, 1, 1, 13990.00),
    (1, 3, 2,   349.90),
    (2, 4, 1,  2199.00),
    (3, 2, 1, 12900.00),
    (3, 5, 3,   500.00),
    (4, 3, 1,   329.00);


-- ---------------------------------------------------------------------------
-- IMPORTANT: resync the identity sequences.
-- Inserting explicit ids does NOT advance the sequence, so the next
-- INSERT without an id would try id=1 and fail on a duplicate key.
-- ---------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT max(id) FROM categories));
SELECT setval(pg_get_serial_sequence('products',   'id'), (SELECT max(id) FROM products));
SELECT setval(pg_get_serial_sequence('customers',  'id'), (SELECT max(id) FROM customers));
SELECT setval(pg_get_serial_sequence('orders',     'id'), (SELECT max(id) FROM orders));

COMMIT;

-- Shows up in `docker compose logs db` so you can confirm this file ran.
DO $$
BEGIN
    RAISE NOTICE 'seed.sql done: % categories, % products, % customers, % orders, % order_items',
        (SELECT count(*) FROM categories),
        (SELECT count(*) FROM products),
        (SELECT count(*) FROM customers),
        (SELECT count(*) FROM orders),
        (SELECT count(*) FROM order_items);
END $$;